import { 
  AccidentesContent,
  CalidadContent,
  DSQContent,
  KaizenContent,
  RHContent,
  FletesContent,
  ControlContent,
  ProduccionContent
} from './tabContents';

export const areaTabs = [
    {id: 'accidentes',
    label: 'Accidentes',
    content: <AccidentesContent />},
    { id: 'calidad',
    label: 'Calidad',
    content: <CalidadContent />},
    { id: 'dias_sin_queja',
    label : 'Días sin queja',
    content: <DSQContent /> },
    { id: 'kaizen',
    label : 'Kaizen',
    content: <KaizenContent /> },
    { id: 'rh',
    label : 'RH',
    content: <RHContent /> },
    { id: 'fletes',
    label : 'Fletes especiales',
    content: <FletesContent /> },
    { id: 'control',
    label : 'Control',
    content: <ControlContent /> },
    { id: 'produccion',
    label : 'Producción',
    content: <ProduccionContent /> },
  ];